version: "3.8"

services:
  animebot_db-dev:
    image: postgres
    container_name: animebot_db-dev
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: animebot
    ports:
      - 5445:5432
  pgadmin-dev:
    image: dpage/pgadmin4
    container_name: pgadmin_db-dev
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_DEFAULT_EMAIL: user@domain.com
    ports:
      - 5050:80



networks:
  default:
    name: animebot_db-env_network