server:
  port: 7500

spring:
  application:
    name: jbot
  datasource:
    url: jdbc:postgresql://127.0.0.1:5445/animebot
    username: admin
    password: admin


management:
  endpoint:
    health:
      show-components: always
      show-details: always
      status:
        http-mapping:
          up: 207
  endpoints:
    web:
      exposure:
        include: health, info, env, beans, metrics
  info:
    env:
      enabled: true
info:
  app:
    name: JBot
    version: 1.0.0

telegram:
  name: ${telegram-name}
  id: ${telegram-id}